import { useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { getTheme } from '@shared-ui/theme/theme';
import { READER_SCREEN_INSET } from '@/constants/layout';

const theme = getTheme(false);

export default function ProfileScreen() {
  const insets = useSafeAreaInsets();
  const [weatherAlerts, setWeatherAlerts] = useState(false);
  const [aboutOpen, setAboutOpen] = useState(false);

  return <View style={styles.screen}>
    <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 160, paddingTop: insets.top + 18 }]}>
      <Text accessibilityRole="header" style={styles.title}>Profile</Text>
      <Text style={styles.subtitle}>Your settings, safety preferences, and account.</Text>
      <View style={styles.identity}><View style={styles.avatar}><Text style={styles.initial}>N</Text></View><View><Text style={styles.name}>Narley Reader</Text><Text style={styles.role}>Community member</Text><Text style={styles.verified}>VERIFIED ACCOUNT</Text></View></View>
      <View style={styles.section}><Text style={styles.sectionTitle}>Safety</Text><View style={[styles.weatherCard, weatherAlerts && styles.weatherActive]}><View style={styles.toggleRow}><Text style={styles.weatherTitle}>Weather alerts</Text><Switch accessibilityLabel="Weather alerts" ios_backgroundColor="#9CA3AF" onValueChange={setWeatherAlerts} thumbColor={weatherAlerts ? '#6B1D14' : theme.colors.primary} trackColor={{ false: '#9CA3AF', true: '#E26D5A' }} value={weatherAlerts} /></View><Text style={styles.description}>Notifications for severe weather, shelter changes, closures, and urgent community conditions.</Text>{weatherAlerts && <Text style={styles.activeBadge}>ACTIVE</Text>}</View></View>
      <View style={styles.section}><Text style={styles.sectionTitle}>Preferences</Text><Pressable style={styles.menuRow}><Text style={styles.menuTitle}>Language</Text><Text style={styles.menuValue}>English</Text></Pressable><Pressable onPress={() => setAboutOpen(true)} style={[styles.menuRow, theme.shadows.card]}><Text style={styles.menuTitle}>About Narley</Text><Text style={styles.chevron}>›</Text></Pressable><Pressable style={styles.feedback}><Text style={styles.feedbackText}>Send feedback</Text></Pressable></View>
      <View style={styles.section}><Text style={styles.sectionTitle}>Account</Text><View style={styles.accountCard}><Text style={styles.accountTitle}>Signed in</Text><Text style={styles.email}>reader@example.com</Text></View></View>
      <Pressable onPress={() => Alert.alert('Log out?', 'You will need to sign in again to access saved resources.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log Out', style: 'destructive' }])} style={styles.logout}><Text style={styles.logoutText}>Log Out</Text></Pressable>
    </ScrollView>
    <Modal animationType="fade" onRequestClose={() => setAboutOpen(false)} transparent visible={aboutOpen}><View style={styles.modalOverlay}><View style={styles.aboutCard}><View style={styles.aboutHeader}><Text style={styles.aboutTitle}>About Narley</Text><Pressable accessibilityLabel="Close About Narley" onPress={() => setAboutOpen(false)} style={styles.aboutClose}><Text style={styles.aboutCloseText}>×</Text></Pressable></View><ScrollView><Text style={styles.aboutSection}>COMMUNITY RESOURCES</Text><Text style={styles.aboutBody}>Narley helps people find practical community resources and timely local updates.</Text><Text style={styles.aboutSection}>OUR APPROACH</Text><Text style={styles.aboutBody}>Information is organized for quick scanning and direct action during stressful situations.</Text><Text style={styles.version}>Version 3</Text></ScrollView></View></View></Modal>
  </View>;
}

const styles = StyleSheet.create({
  screen: { backgroundColor: theme.colors.appBackground, flex: 1 }, content: { paddingHorizontal: READER_SCREEN_INSET }, title: { color: theme.colors.textInverse, fontSize: 32, fontWeight: '900', marginBottom: 4 }, subtitle: { color: '#9CA3AF', fontSize: 15, marginBottom: 18 },
  identity: { ...theme.shadows.card, alignItems: 'center', backgroundColor: theme.colors.background, borderRadius: 24, flexDirection: 'row', marginBottom: 24, padding: 16 }, avatar: { alignItems: 'center', backgroundColor: theme.colors.primary, borderRadius: 27, height: 54, justifyContent: 'center', marginRight: 14, width: 54 }, initial: { color: theme.colors.textInverse, fontSize: 24, fontWeight: '900' }, name: { color: theme.colors.text, fontSize: 15, fontWeight: '900' }, role: { color: theme.colors.textMuted, fontSize: 13, fontWeight: '600' }, verified: { color: '#0F766E', fontSize: 12, fontWeight: '900', marginTop: 6 },
  section: { marginBottom: 24 }, sectionTitle: { color: theme.colors.textInverse, fontSize: 17, fontWeight: '900', marginBottom: 10 }, weatherCard: { ...theme.shadows.card, backgroundColor: theme.colors.background, borderRadius: 24, padding: 16 }, weatherActive: { borderColor: '#E26D5A', borderWidth: 2 }, toggleRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }, weatherTitle: { color: theme.colors.text, flex: 1, fontSize: 18, fontWeight: '900', paddingRight: 12 }, description: { color: '#4B5563', fontSize: 14, lineHeight: 20 }, activeBadge: { alignSelf: 'flex-start', backgroundColor: '#8B2E24', borderRadius: 999, color: theme.colors.textInverse, fontSize: 12, fontWeight: '900', letterSpacing: 1, marginTop: 14, overflow: 'hidden', paddingHorizontal: 12, paddingVertical: 6 },
  menuRow: { alignItems: 'center', backgroundColor: theme.colors.background, borderRadius: 20, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, padding: 16 }, menuTitle: { color: theme.colors.text, fontSize: 15, fontWeight: '800' }, menuValue: { color: theme.colors.textMuted, fontSize: 13, fontWeight: '700' }, chevron: { color: theme.colors.primary, fontSize: 28, fontWeight: '900' }, feedback: { ...theme.shadows.card, alignItems: 'center', backgroundColor: theme.colors.primary, borderRadius: 16, paddingVertical: 14 }, feedbackText: { color: theme.colors.textInverse, fontSize: 15, fontWeight: '900' },
  accountCard: { ...theme.shadows.card, backgroundColor: theme.colors.background, borderRadius: 24, padding: 16 }, accountTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '900', marginBottom: 12 }, email: { color: '#4B5563', fontSize: 15, fontWeight: '700' }, logout: { alignItems: 'center', backgroundColor: '#8B2E24', borderRadius: 16, marginBottom: 24, paddingVertical: 14 }, logoutText: { color: theme.colors.textInverse, fontSize: 15, fontWeight: '900' },
  modalOverlay: { alignItems: 'center', backgroundColor: 'rgba(2,6,23,0.72)', flex: 1, justifyContent: 'center', padding: 18 }, aboutCard: { ...theme.shadows.card, backgroundColor: theme.colors.background, borderRadius: 24, maxHeight: '82%', padding: 16, width: '100%' }, aboutHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 14 }, aboutTitle: { color: theme.colors.text, fontSize: 22, fontWeight: '900' }, aboutClose: { alignItems: 'center', backgroundColor: theme.colors.border, borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }, aboutCloseText: { color: theme.colors.text, fontSize: 16, fontWeight: '900' }, aboutSection: { color: theme.colors.primary, fontSize: 15, fontWeight: '900', marginBottom: 6, marginTop: 12 }, aboutBody: { color: '#4B5563', fontSize: 15, fontWeight: '600', lineHeight: 22 }, version: { color: theme.colors.text, fontSize: 13, fontWeight: '900', marginTop: 18 },
});
